# Site wide configuration

title:            Stu MacDonald
locale:           en_US
url:              http://stumacdonald.com

# Jekyll configuration

lsi: false
safe: true
source: www.github.com/stumacd/stumacdonald.github.io
incremental: false
highlighter: rouge
gist:
  noscript: false

permalink:   /:categories/:title/
markdown:    kramdown
#highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
  math_engine: mathjax
  syntax_highlighter: rouge
  

# Site owner
owner:
  name: Stu MacDonald
  avatar: bio-photo.jpg
  bio: "Developer. Engineer. Hobbyist."
  email: stumacd@gmail.com
  disqus-shortname: 
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: stumacd
  stackoverflow: 255816/stu
  linkedin: stumacdonald82
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username

gems: ['kramdown']
include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md",'config.ru', 'vendor','Procfile']
